version: '3.3'

services:
  mongo:
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
